"""Build the accessible architecture page from the Rev B drawing manifest."""
from pathlib import Path
import json,re
from html import escape as e
from seo_common import decorate
ROOT=Path(__file__).resolve().parents[1]
figs=json.loads((ROOT/'assets/schematics/rev-b/manifest.json').read_text())
home=(ROOT/'index.html').read_text(encoding='utf-8')
header=re.search(r'<header.*?</header>',home,re.S).group()
header=re.sub(r'href="#([^"]+)"',r'href="index.html#\1"',header).replace('href="architecture.html"','href="architecture.html" aria-current="page"')
footer=re.search(r'<footer>.*?</footer>',home,re.S).group().replace('href="#top"','href="#mission"')
sources=[
 ('photosynthesis','DOE · Solar Fuels','https://www.energy.gov/science/doe-explainssolar-fuels','Solar-driven water splitting and carbon-dioxide reduction are research pathways; chemistry and energy conversion must be specified.'),
 ('terraforming','NASA · Mars Terraforming study (2018)','https://www.nasa.gov/news-release/mars-terraforming-not-possible-using-present-day-technology/','The study finds accessible Martian CO₂ insufficient for its proposed greenhouse-warming route with present-day technology; it does not test this satellite concept.'),
 ('thermal','NASA · Small Spacecraft Thermal Control','https://www.nasa.gov/smallsat-institute/sst-soa/thermal-control/','Thermal radiation, conductive heat paths, coatings, and active/passive control.'),
 ('power','NASA · Mars 2020 MMRTG','https://science.nasa.gov/resource/mars-2020s-mmrtg/','Approximately 110 W of electrical power at mission start; a reference system, not a proposed node specification.'),
 ('decay','NASA · Radioisotope Power Systems FAQ','https://science.nasa.gov/planetary-science/programs/radioisotope-power-systems/faq/','Pu-238 decay and power-system context; decay is not spacecraft qualification.'),
 ('compute','Nature · All-analog photoelectronic chip for high-speed vision tasks (2023)','https://www.nature.com/articles/s41586-023-06558-8','A workload-specific laboratory demonstration with system-level energy accounting; not evidence of this spacecraft’s performance.'),
 ('memory','Nature Communications · One-hour coherent optical storage (2021)','https://www.nature.com/articles/s41467-021-22706-y','Laboratory coherent storage in a rare-earth crystal; not a general-purpose, years-long orbital archive.'),
 ('network','NASA · Delay/Disruption Tolerant Networking','https://www.nasa.gov/reference/delay-disruption-tolerant-networking-overview/','Store-and-forward networking and bundle authentication, integrity, and encryption.'),
 ('links','JPL · Deep Space Optical Communications','https://www.jpl.nasa.gov/missions/deep-space-optical-communications-dsoc/','267 Mbps demonstrated at 31 million km in December 2023; this is a specific experiment, not a universal link rate.'),
 ('oxygen','NASA · MOXIE completes Mars mission','https://www.nasa.gov/solar-system/nasas-oxygen-generating-experiment-moxie-completes-mars-mission/','A separate oxygen-production experiment reached 12 g/hour at 98% purity or better; it does not validate orbital photosynthesis forecasts.'),
]
cards=''.join(f'<figure class="drawing" id="drawing-{i}" aria-labelledby="drawing-title-{i}"><a href="{f["src"]}" target="_blank" rel="noopener" aria-label="Open full-size {e(f["title"])}"><img src="{f["src"]}" alt="{e(f["desc"])}" width="1200" height="760" {"" if i==0 else "loading=\"lazy\""}></a><figcaption><div><p class="eyebrow">FIGURE {i+1:02} / REV B</p><h3 id="drawing-title-{i}">{e(f["title"])}</h3><p>{e(f["desc"])}</p></div><a class="text-link" href="{f["src"]}" target="_blank" rel="noopener">Open full-size SVG ↗</a></figcaption></figure>' for i,f in enumerate(figs))
buttons=''.join(f'<button type="button" data-figure="{i}" aria-controls="drawing-{i}" aria-pressed="false"><span>{i+1:02}</span>{e(name)}</button>' for i,name in enumerate(['Satellite bus','Photonic core','Storage node','Orbital network','Power & thermal','Symbol encoding','Security','Research boundary','Photosynthesis','Interferometer']))
source_html=''.join(f'<li id="source-{id}"><a href="{url}" target="_blank" rel="noopener">{e(title)} ↗</a><p>{e(desc)}</p></li>' for id,title,url,desc in sources)
originals=''.join(f'<li><a href="assets/schematics/{p.name}" target="_blank" rel="noopener">{e(p.stem.replace("-"," "))} ↗</a></li>' for p in sorted((ROOT/'assets/schematics').glob('*.png')))
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Photonic Architecture — Goldstar Orbital</title><meta name="description" content="Explore eight revised orbital schematics: a hybrid photonic accelerator, spacecraft bus, active storage nodes, thermal design, and a measured path to flight."><meta name="theme-color" content="#080a0b"><link rel="canonical" href="https://goldstarorbital.com/architecture"><link rel="icon" href="assets/favicon-32.png">
<meta property="og:title" content="Photonic Architecture — Goldstar Orbital"><meta property="og:description" content="A clearer architecture. A measured path to the frontier."><meta property="og:image" content="https://goldstarorbital.com/assets/orbital-hero.jpg">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&amp;family=Space+Mono&amp;display=swap" rel="stylesheet"><link rel="stylesheet" href="site.css"><link rel="stylesheet" href="architecture.css"><script src="architecture.js" defer></script></head><body class="architecture-page"><a class="skip" href="#mission">Skip to content</a>'''+header+'''
<main id="mission"><section class="arch-hero section"><p class="eyebrow">RESEARCH &amp; DEVELOPMENT / REVISION B · SEPTEMBER 2026</p><h1>Compute in light.<br><em>Engineer for space.</em></h1><p class="intro">A hybrid photonic architecture for the next frontier. Designed around the systems that make an experiment possible: power, cooling, memory, communications, and control.</p><div class="hero-actions"><a class="button" href="#schematics">Explore the schematics ↘</a><a class="text-link" href="#engineering">Read the engineering review ↗</a></div><p class="concept-label">CONCEPT STUDY · PROPOSED DESIGN · NOT FLIGHT-QUALIFIED</p></section>
<section class="section" id="schematics"><div class="section-heading"><div><p class="eyebrow">01 / THE SYSTEM, DRAWN CLEARLY</p><h2>From photon<br>to flight system.</h2></div><p>Eight original vector drawings.<br>Open any diagram to inspect every label.</p></div><div id="figure-buttons" class="figure-buttons" hidden role="group" aria-label="Select a schematic">'''+buttons+'''</div><div class="drawings">'''+cards+'''</div><div id="gallery-controls" class="gallery-controls" hidden><button id="previous-figure" type="button" aria-label="Previous figure">← Previous</button><span id="figure-count" aria-live="polite">1 / 8</span><button id="next-figure" type="button" aria-label="Next figure">Next →</button></div></section>
<section class="section" id="engineering"><div class="section-heading"><div><p class="eyebrow">02 / ENGINEERING REVIEW</p><h2>Ambition, with<br>the budgets attached.</h2></div><p>Revised assumptions.<br>Explicit evidence boundaries.</p></div>
<div class="review-grid">
<article><span class="review-tag">COMPUTE / REVISED</span><h3>A hybrid accelerator.</h3><p>The photonic core handles selected matrix operations. Electronic memory, scheduling, conversion, readout, and calibration remain visible. Replace the blanket 20,000× efficiency and exaFLOP claims with a measured comparison at equal precision, accuracy, and workload.</p><a href="#source-compute">Research context ↗</a></article>
<article><span class="review-tag">THERMAL / CORRECTED</span><h3>Vacuum still needs a radiator.</h3><p>Vacuum removes convection. It does not eliminate losses or stabilize the chip to millikelvin precision. Add conductive heat paths, a radiator, sensors, and phase feedback; qualify performance through orbital hot/cold cases.</p><a href="#source-thermal">NASA thermal guidance ↗</a></article>
<article><span class="review-tag">STORAGE / REVISED</span><h3>Persist data in a proven form.</h3><p>Use ECC nonvolatile storage as the baseline and test optical memory separately. The former “passive” node also needs command authentication, health monitoring, and pointing control. Months-to-years quantum retention is not established by the cited laboratory storage work.</p><a href="#source-memory">Optical-memory evidence ↗</a></article>
<article><span class="review-tag">POWER / OPEN TRADE</span><h3>Size the source to the mission.</h3><p>Start with solar and battery power for an Earth-orbit demonstrator. Trade a radioisotope source for later missions against mass, heat, availability, and end-of-life power. Pu-238 decay alone cannot certify a 50–100 year service life.</p><a href="#source-power">NASA reference system ↗</a> · <a href="#source-decay">Decay context ↗</a></article>
<article><span class="review-tag">COMMUNICATIONS / REVISED</span><h3>Design for contact windows.</h3><p>Separate local optical links from the Earth–Mars link budget. Include aperture, range, pointing jitter, receiver sensitivity, and coding. Buffer traffic between contacts and provide an independent recovery link; no universal 100 Gbps rate is assumed.</p><a href="#source-links">DSOC benchmark ↗</a> · <a href="#source-network">DTN architecture ↗</a></article>
<article><span class="review-tag">OXYGEN / RESEARCH ONLY</span><h3>A separate experiment.</h3><p>Keep surface chemistry as an optional research program with its own reactor, feedstock, energy, and optical-delivery budgets. Remove kg/day and terraforming schedules inferred from node counts. MOXIE offers a measured reference for oxygen production, not proof of this concept.</p><a href="#source-oxygen">NASA experiment ↗</a></article></div>
<details class="technical-details"><summary>Open the quantitative checks</summary><div class="checks"><article><h3>The alphabet is 26 ideal bits.</h3><p><code>log₂(256 × 64 × 16 × 256) = 26</code></p><p>The original state counts give 8 + 6 + 4 + 8 bits, not 32. This assumes independent, distinguishable states. It is not a demonstrated number of bits per photon or a storage-density multiplier. Measure errors, mutual information, and net coded throughput.</p></article>
<article><h3>Capacity scales consistently.</h3><p>Illustration only: at an assumed 10 TB per node, 1,000 nodes yield 10 PB raw; 100,000 yield 1 EB raw; one million yield 10 EB raw. These use decimal units. Actual density is unvalidated; redundancy, ECC, spare capacity, and unavailable nodes reduce usable storage.</p></article>
<article><h3>Cooling has a first-order area.</h3><p><code>A ≈ Q / [εσ(T⁴ − Tspace⁴)]</code></p><p>With Q = 100 W, ε = 0.85, T = 300 K, and an ideal 3 K sink, A ≈ 0.26 m² of emitting area. This illustrative calculation omits absorbed sunlight, planetary IR, view factors, temperature gradients, source heat, and design margin. It is not flight sizing.</p></article>
<article><h3>Decay is one part of the budget.</h3><p><code>Heat fraction = 2^(−years / 87.7)</code></p><p>About 67% of initial isotope heat remains after 50 years and 45% after 100. Converter degradation and subsystem failures further limit usable electrical output and mission life. No 1–5 kg radioisotope-powered node has been validated here.</p></article></div></details>
</section>
<section class="section" id="roadmap"><p class="eyebrow">03 / A MEASURED PATH TO FLIGHT</p><h2>Earn the next step.</h2><p class="section-intro">Proposed development gates, not a funded schedule or a claim that these milestones are complete.</p><ol class="roadmap"><li><span>01 / BENCH</span><h3>Measure the payload.</h3><p>Compare against an electronic baseline. Record total power, task accuracy, useful throughput, and phase drift across temperature.</p></li><li><span>02 / QUALIFICATION</span><h3>Close the flight budgets.</h3><p>Set measurable acceptance limits for thermal vacuum, radiation, vibration, pointing, power, storage errors, and safe-mode recovery.</p></li><li><span>03 / DEMONSTRATION</span><h3>Test a small orbital system.</h3><p>Validate contact recovery, onboard workloads, data integrity, and model agreement on a limited demonstrator.</p></li><li><span>04 / EXPANSION</span><h3>Scale from evidence.</h3><p>Model coverage, capacity, orbital maintenance, mass, cost, and replenishment before selecting a Mars constellation.</p></li></ol></section>
<section class="section" id="references"><p class="eyebrow">04 / EVIDENCE &amp; DESIGN HISTORY</p><h2>Open assumptions.<br>Traceable references.</h2><p class="section-intro">These sources inform the revision. They do not endorse Goldstar Orbital, certify its hardware, or establish supplier relationships.</p><ol class="sources">'''+source_html+'''</ol>
<details class="technical-details"><summary>Original concept drawings · historical reference</summary><p>The nine original drawings remain available below. They contain superseded performance, capacity, lifetime, vendor, and security assumptions; use Revision B for the current proposed architecture.</p><ul class="originals">'''+originals+'''</ul></details>
<details class="technical-details"><summary>Patent-family notes from the original site</summary><p>Owner-provided filing descriptions, preserved for continuity. Filing status, claim scope, and priority have not been independently verified in this engineering review.</p><ul class="patents"><li><strong>Patent 1 · reported filed May 22, 2026.</strong> Photonic Orbital Data Storage, Non-Binary Encoding, and Multi-Symbol Energy-State Communication System</li><li><strong>Patent 2 · reported filed.</strong> Orbital Photonic Compute-Memory System with Vacuum-Enabled Interferometric Performance &amp; Radioisotope-Sustained Storage</li><li><strong>Patent 3A · planned.</strong> Photon-Driven Artificial Photosynthetic Process for Planetary Atmosphere Generation</li><li><strong>Patent 3B · planned, keystone.</strong> Orbital Photonic GPU Real-Time Wavelength Optimization System for Photosynthetic Reaction Control</li><li><strong>Patent 3C · planned.</strong> Integrated Orbital Photonic Data and Planetary Atmosphere Generation System</li></ul></details>
</section><section class="section contact" id="contact"><p class="eyebrow">05 / BUILD WITH US</p><h2>The next breakthrough<br>starts with <em>a question.</em></h2><a class="button" href="mailto:alexgoldsmith@goldstarorbital.com">Discuss the architecture ↗</a></section></main>'''+footer+'''</body></html>'''
terraform='''<section class="section terraform" id="photosynthesis"><p class="eyebrow">THE LONG VIEW / PHOTOSYNTHESIS &amp; MARS</p><h2>From light.<br><em>Toward life.</em></h2><p class="section-intro">Our long-term vision is a satellite network that could help coordinate surface photosynthesis experiments, with the eventual ambition of contributing to Mars habitability and terraforming research.</p><a href="assets/schematics/rev-b/photosynthesis.svg" target="_blank" rel="noopener"><img src="assets/schematics/rev-b/photosynthesis.svg" alt="Proposed satellite-to-surface photosynthesis loop with optical delivery, a contained reactor, and telemetry feedback" width="1200" height="760" loading="lazy" style="width:100%;height:auto"></a><div class="terraform-grid"><article><h3>A proposed satellite-assisted loop.</h3><p>Surface sensors would report reactor temperature, illumination, and oxygen output. Orbital compute could help select experimental wavelength and timing settings. A future dedicated optical payload could test tuned light delivery during contact windows, alongside a comparison with locally powered illumination.</p><p>The reactor would need a defined catalyst or biological process, water and other feedstocks, thermal control, and oxygen collection. In oxygenic photosynthesis, the released oxygen comes from water; a generic “CO₂ to O₂” arrow leaves essential chemistry out. <a href="#source-photosynthesis">DOE research context ↗</a></p></article><article><h3>Prove the reactor before the planet.</h3><p>First measure oxygen per unit of total energy in a contained system under relevant environmental conditions. Then test whether satellite coordination or beamed illumination improves that result after all losses. Compute efficiency cannot supply the chemical reaction’s energy.</p><p class="research-note">These are proposed capabilities, not completed tests. Oxygen production alone does not create a breathable Mars: atmospheric pressure, temperature, total mass, retention, and long-term energy supply remain unresolved. No terraforming date or production yield is established. <a href="#source-terraforming">NASA study context ↗</a></p></article></div></section>'''
html=html.replace('<section class="section" id="roadmap">',terraform+'<section class="section" id="roadmap">')
html=html.replace('href="architecture.css"','href="architecture.css"').replace('</head>','<link rel="stylesheet" href="space.css"><script src="space.js" defer></script></head>')
html=html.replace('eight revised','ten revised').replace('Eight original','Ten original').replace('1 / 8','1 / 10')
html=html.replace('Compute in light.<br><em>Engineer for space.</em>','Photonic computing.<br><em>Engineered for space.</em>')
html=html.replace('From photon<br>to flight system.','Photonic spacecraft<br>schematics.')
html=html.replace('<section class="section" id="engineering">','<aside class="architecture-reading"><h2>Understand the design choices</h2><p><a href="/photonic-computing">How photonic computing works</a> · <a href="/orbital-infrastructure">Power, cooling, and orbital networks</a> · <a href="/mars-photosynthesis">Photosynthesis and Mars research</a></p></aside><section class="section" id="engineering">')
(ROOT/'architecture.html').write_text(decorate(html,'/architecture'),encoding='utf-8')
print('Built architecture.html')
